### PR TITLE
Update gem for rails 5

### PR DESCRIPTION
**Pull request by artsiom-lahun**

### CODE REVIEW

File: lib/pg_sequencer/schema_dumper.rb [hunk 1]
```diff
@@ -22,7 +22,7 @@ module SchemaDumper
     extend ActiveSupport::Concern
 
     included do
-      alias_method_chain :tables, :sequences
+      alias_method :tables, :sequences
```
Comment (ilchanka) [inline lib/pg_sequencer/schema_dumper.rb]: alias_method alias_method_chain this 2 methods are not equivalent

Comment (artsiom-lahun) [reply lib/pg_sequencer/schema_dumper.rb]: when I updated service from rails 4.2.7.1 to 5.1.0 and ran specs, rails wrote:
NoMethodError:
  undefined method `alias_method_chain' for ActiveRecord::SchemaDumper:Class
  Did you mean?  alias_method

by this reason I added these changes into this gem

File: pg_sequencer.gemspec [hunk 2]
```diff
@@ -17,9 +17,9 @@ Gem::Specification.new do |s|
   s.test_files = Dir["test/**/*"]
 
   # s.add_dependency "rails", "~> 3.1.0"
-  s.add_dependency 'activerecord', '>= 3.1.0'
+  s.add_dependency 'activerecord', '>= 5.1.0'
```
Comment (ilchanka) [inline pg_sequencer.gemspec]: I don't see any changes specific to activerecord, so looks like it can work with previous versions of AR, no need to do >= 5.1 I think

File: lib/pg_sequencer/schema_dumper.rb (hunk 1 above)
Comment (ilchanka) [reply lib/pg_sequencer/schema_dumper.rb]: please read how to replace alias_method_chain 
http://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/

**Comment by artsiom-lahun** [comment]
@ilchanka @yury-kaspiarovich could check again? I've remove alias_method_chain and use Module#prepend.

**Review by ilchanka — APPROVED** [review]
